In [17]:
a = 1; print(type(a))

<class 'int'>


int: 정수

class type은 암기!

print 라는 함수를 이용하여 무언가를 출력

In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


float: 소수

In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


string : 문자 

따옴표를 양쪽에 붙여주는건 그것을 문자열로 보겠다는 의미. 문자열 처리시 작은따옴표를 사용하건 큰따옴표를 사용하나 큰 지장이 없다.

'123' : 문자

0은 첫번째 문자, 1은 두번째, ... -1은 가장 마지막 문자를 의미함.

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


QQQ. print(a)를 하든, a를 하든 output이 똑같은데 어떤 차이가 있나? 

In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


대괄호[] 사용. 숫자이기 때문.

QQQ. 2로 하지 않고 '2'로 한 이유 --- '2'는 글자?

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


tuple은 list와 성격이 같다

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


dict: dictionary 

[] : 실행 

() : 찾기

dictionary 쓸 때는 {} 중괄호 사용. 숫자가 아니기 때문에.

In [14]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [15]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [16]:
import numpy
b = numpy.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


두번째줄 array만 쓰면 에러남.

array는 matrix 비슷.

import: 하드디스크에 다운로드 받고 메모리에 올리는 것

NumPy(numerical python) : 행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리 할 수 있도록 지원하는 파이썬의 라이브러리이다. NumPy는 데이터 구조 외에도 수치 계산을 위해 효율적으로 구현된 기능을 제공한다.

array: 함수

ndarray : array 함수로 만든 다차원 배열의 데이터 타입

In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [17]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


numpy matrix: Returns a matrix from an array-like object, or from a string of data.

In [18]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

array와 matrix는 이래서 다르다. 
matrix는 (2,3)행렬과 (2,3)행렬이 곱해질 수 없음.

In [21]:
c*c.T

matrix([[14, 19],
        [19, 73]])

T: transpose

(2,3)행렬 X (3,2)행렬 = (2,2)행렬

이 수업에서 숫자적으로는 numpy가 제일 중요! 

In [22]:
c.T*c

matrix([[10, 26,  3],
        [26, 68,  6],
        [ 3,  6,  9]])

In [23]:
s = 'abcdef'

In [24]:
type(s)

str

In [25]:
print(type(s))

<class 'str'>
